type InstrumentType = {
  piano: { [note: string]: string[] };
  guitar: { [note: string]: string[] };
  drums: { [note: string]: string[] };
  bass: { [note: string]: string[] };
};

const instrumentRanges: InstrumentType =
  {
    piano: {
      A: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      Ab: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      B: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      C: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
      ],
      Cb: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      D: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      Db: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      E: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      F: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      Fb: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      G: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      Gb: [
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
    },
    guitar: {
      A: [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      Ab: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      B: [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      Bb: [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      C: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      D: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      Db: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      E: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      Eb: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      F: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      G: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
      Gb: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
      ],
    },
    bass: {
      E: ["1", "2", "3"],
      A: ["1", "2", "3"],
      D: ["1", "2", "3"],
      G: ["1", "2", "3"],
    },
    drums: {
      clap: [
        "808",
        "analog",
        "crushed",
        "fat",
        "slapper",
        "tape",
      ],
      cowbell: ["808"],
      crash: [
        "808",
        "acoustic",
        "noise",
        "tape",
      ],
      hihat: [
        "808",
        "acoustic01",
        "acoustic02",
        "analog",
        "digital",
        "dist01",
        "dist02",
        "electro",
        "plain",
        "reso",
        "ring",
      ],
      kick: [
        "808",
        "acoustic01",
        "acoustic02",
        "big",
        "classic",
        "cultivator",
        "deep",
        "dry",
        "electro01",
        "electro02",
        "floppy",
        "gritty",
        "heavy",
        "newwave",
        "oldschool",
        "plain",
        "slapback",
        "softy",
        "stomp",
        "tape",
        "thump",
        "tight",
        "tron",
        "vinyl01",
        "vinyl02",
        "zapper",
      ],
      openhat: [
        "808",
        "acoustic01",
        "analog",
        "slick",
        "tight",
      ],
      perc: [
        "808",
        "chirpy",
        "hollow",
        "laser",
        "metal",
        "nasty",
        "short",
        "tambo",
        "tribal",
        "weirdo",
      ],
      ride: [
        "acoustic01",
        "acoustic02",
      ],
      shaker: [
        "analog",
        "shuffle",
        "suckup",
      ],
      snare: [
        "808",
        "acoustic01",
        "acoustic02",
        "analog",
        "big",
        "block",
        "brute",
        "dist01",
        "dist02",
        "dist03",
        "electro",
        "lofi01",
        "lofi02",
        "modular",
        "noise",
        "pinch",
        "punch",
        "smasher",
        "sumo",
        "tape",
        "vinyl01",
        "vinyl02",
      ],
      tom: [
        "808",
        "acoustic01",
        "acoustic02",
        "analog",
        "chiptune",
        "fm",
        "lofi",
        "rototom",
        "short",
      ],
    },
  };

export default instrumentRanges;
